import type {
  erd,
  erd_column,
  erd_relationships,
  erd_table,
} from "../types/erd";

export const ERD: erd[] = [
  { erd_id: 1, created_at: new Date(), workspace_id: 3 },
  { erd_id: 2, created_at: new Date(), workspace_id: 12 },
];

export const ERD_TABLE: erd_table[] = [
  { erd_table_id: 1, name: "Users", erd_id: 1 },
  { erd_table_id: 2, name: "Posts", erd_id: 1 },
  { erd_table_id: 3, name: "Comments", erd_id: 1 },
  { erd_table_id: 4, name: "Categories", erd_id: 1 },
  { erd_table_id: 5, name: "Post_Categories", erd_id: 1 },
  { erd_table_id: 6, name: "Categories", erd_id: 12 },
  { erd_table_id: 7, name: "Post_Categories", erd_id: 12 },
];

export const ERD_COLUMN: erd_column[] = [
  {
    erd_column_id: 1,
    erd_table_id: 1,
    name: "id",
    data_type: "INT",
    is_primary_key: true,
    is_foreign_key: false,
    is_nullable: false,
  },
  {
    erd_column_id: 2,
    erd_table_id: 1,
    name: "username",
    data_type: "VARCHAR(50)",
    is_primary_key: false,
    is_foreign_key: false,
    is_nullable: false,
  },
  {
    erd_column_id: 3,
    erd_table_id: 1,
    name: "email",
    data_type: "VARCHAR(100)",
    is_primary_key: false,
    is_foreign_key: false,
    is_nullable: false,
  },

  {
    erd_column_id: 4,
    erd_table_id: 2,
    name: "id",
    data_type: "INT",
    is_primary_key: true,
    is_foreign_key: false,
    is_nullable: false,
  },
  {
    erd_column_id: 5,
    erd_table_id: 2,
    name: "user_id",
    data_type: "INT",
    is_primary_key: false,
    is_foreign_key: true,
    is_nullable: false,
  },
  {
    erd_column_id: 6,
    erd_table_id: 2,
    name: "title",
    data_type: "VARCHAR(200)",
    is_primary_key: false,
    is_foreign_key: false,
    is_nullable: false,
  },
  {
    erd_column_id: 7,
    erd_table_id: 2,
    name: "content",
    data_type: "TEXT",
    is_primary_key: false,
    is_foreign_key: false,
    is_nullable: true,
  },

  {
    erd_column_id: 8,
    erd_table_id: 3,
    name: "id",
    data_type: "INT",
    is_primary_key: true,
    is_foreign_key: false,
    is_nullable: false,
  },
  {
    erd_column_id: 9,
    erd_table_id: 3,
    name: "post_id",
    data_type: "INT",
    is_primary_key: false,
    is_foreign_key: true,
    is_nullable: false,
  },
  {
    erd_column_id: 10,
    erd_table_id: 3,
    name: "user_id",
    data_type: "INT",
    is_primary_key: false,
    is_foreign_key: true,
    is_nullable: false,
  },
  {
    erd_column_id: 11,
    erd_table_id: 3,
    name: "comment",
    data_type: "TEXT",
    is_primary_key: false,
    is_foreign_key: false,
    is_nullable: true,
  },

  {
    erd_column_id: 12,
    erd_table_id: 4,
    name: "id",
    data_type: "INT",
    is_primary_key: true,
    is_foreign_key: false,
    is_nullable: false,
  },
  {
    erd_column_id: 13,
    erd_table_id: 4,
    name: "name",
    data_type: "VARCHAR(100)",
    is_primary_key: false,
    is_foreign_key: false,
    is_nullable: false,
  },

  {
    erd_column_id: 14,
    erd_table_id: 5,
    name: "post_id",
    data_type: "INT",
    is_primary_key: true,
    is_foreign_key: true,
    is_nullable: false,
  },
  {
    erd_column_id: 15,
    erd_table_id: 5,
    name: "category_id",
    data_type: "INT",
    is_primary_key: true,
    is_foreign_key: true,
    is_nullable: false,
  },
];

export const ERD_RELATION: erd_relationships[] = [
  {
    erd_relationships_id: 1,
    type: "ONE_TO_MANY",
    foreign_key: "user_id",
    constraint_name: "fk_posts_users",
    from_erd_table_id: 2,
    to_erd_table_id: 1,
  },
  {
    erd_relationships_id: 2,
    type: "ONE_TO_MANY",
    foreign_key: "user_id",
    constraint_name: "fk_comments_users",
    from_erd_table_id: 3,
    to_erd_table_id: 1,
  },
  {
    erd_relationships_id: 3,
    type: "ONE_TO_MANY",
    foreign_key: "post_id",
    constraint_name: "fk_comments_posts",
    from_erd_table_id: 3,
    to_erd_table_id: 2,
  },
  {
    erd_relationships_id: 4,
    type: "MANY_TO_MANY",
    foreign_key: undefined,
    constraint_name: "fk_post_categories",
    from_erd_table_id: 5,
    to_erd_table_id: 4,
  },
  {
    erd_relationships_id: 5,
    type: "MANY_TO_MANY",
    foreign_key: undefined,
    constraint_name: "fk_post_categories",
    from_erd_table_id: 5,
    to_erd_table_id: 2,
  },
];
