import type { workspace } from "../types/workspace";
import type { workspace_member } from "../types/workspace";

export const dummyWorkspaces: workspace[] = [
  {
    workspace_id: 1,
    owner_id: 1,
    team_name: "SmartCity Team A1",
    project_name: "Air Quality Monitoring1",
    created_at: new Date("2024-11-01T10:00:00Z"),
    is_public: true,
    progress_step: 0,
  },
  {
    workspace_id: 2,
    owner_id: 1,
    team_name: "CityVision Team",
    project_name: "Bus Stop Usage Optimization",
    created_at: new Date("2025-02-15T15:30:00Z"),
    project_target: "Analyze and optimize passenger flow at smart bus stops.",
    project_description:
      "Uses sensor and statistical data to understand and improve bus stop usage patterns.",
    project_summary: "Enhancing efficiency in public transport waiting zones.",
    project_features: JSON.stringify([
      "Usage heatmaps",
      "Peak-hour traffic prediction",
      "Smart routing suggestions",
    ]),
    is_public: false,
    progress_step: 1,
  },
  {
    workspace_id: 3,
    owner_id: 1,
    team_name: "CityVision Team",
    project_name: "Bus Stop Usage Optimization",
    created_at: new Date("2025-02-15T15:30:00Z"),
    project_target: "Analyze and optimize passenger flow at smart bus stops.",
    project_description:
      "Uses sensor and statistical data to understand and improve bus stop usage patterns.",
    project_summary: "Enhancing efficiency in public transport waiting zones.",
    project_features: JSON.stringify([
      "Usage heatmaps",
      "Peak-hour traffic prediction",
      "Smart routing suggestions",
    ]),
    is_public: false,
    progress_step: 6,
  },
  {
    workspace_id: 4,
    owner_id: 1,
    team_name: "SmartCity Team A",
    project_name: "Air Quality Monitoring",
    created_at: new Date("2024-11-01T10:00:00Z"),
    project_target: "Improve urban air quality around bus stops.",
    project_description:
      "This project collects air quality data from various bus stops and analyzes it to improve environmental health conditions.",
    project_summary: "An IoT and data-driven approach to urban air quality.",
    project_features: JSON.stringify([
      "Real-time PM10/PM2.5 sensors",
      "Public dashboard",
      "Alert system for poor air",
    ]),
    is_public: false,
    progress_step: 5,
  },
  {
    workspace_id: 5,
    owner_id: 1,
    team_name: "SmartCity Team A",
    project_name: "Air Quality Monitoring",
    created_at: new Date("2024-11-01T10:00:00Z"),
    project_target: "Improve urban air quality around bus stops.",
    project_description:
      "This project collects air quality data from various bus stops and analyzes it to improve environmental health conditions.",
    project_summary: "An IoT and data-driven approach to urban air quality.",
    project_features: JSON.stringify([
      "Real-time PM10/PM2.5 sensors",
      "Public dashboard",
      "Alert system for poor air",
    ]),
    is_public: false,
    progress_step: 4,
  },
  {
    workspace_id: 6,
    owner_id: 1,
    team_name: "SmartCity Team A",
    project_name: "Air Quality Monitoring",
    created_at: new Date("2024-11-01T10:00:00Z"),
    project_target: "Improve urban air quality around bus stops.",
    project_description:
      "This project collects air quality data from various bus stops and analyzes it to improve environmental health conditions.",
    project_summary: "An IoT and data-driven approach to urban air quality.",
    project_features: JSON.stringify([
      "Real-time PM10/PM2.5 sensors",
      "Public dashboard",
      "Alert system for poor air",
    ]),
    is_public: true,
    progress_step: 3,
  },
];

export const dummyWSMember: workspace_member[] = [
  {
    workspace_member_id: 1,
    user_id: 1,
    workspace_id: 1,
    role: "OWNER",
    joined_at: new Date("2024-11-01T10:00:00Z"),
  },
  {
    workspace_member_id: 2,
    user_id: 2,
    workspace_id: 1,
    role: "MEMBER",
    joined_at: new Date("2024-11-01T10:00:00Z"),
  },
  {
    workspace_member_id: 3,
    user_id: 3,
    workspace_id: 1,
    role: "GUEST",
    joined_at: new Date("2024-11-01T10:00:00Z"),
  },
  {
    workspace_member_id: 4,
    user_id: 1,
    workspace_id: 3,
    role: "OWNER",
    joined_at: new Date("2024-11-01T10:00:00Z"),
  },
  {
    workspace_member_id: 5,
    user_id: 2,
    workspace_id: 3,
    role: "MEMBER",
    joined_at: new Date("2024-11-01T10:00:00Z"),
  },
  {
    workspace_member_id: 6,
    user_id: 3,
    workspace_id: 3,
    role: "GUEST",
    joined_at: new Date("2024-11-01T10:00:00Z"),
  },
  {
    workspace_member_id: 7,
    user_id: 4,
    workspace_id: 3,
    role: "MEMBER",
    joined_at: new Date("2024-11-01T10:00:00Z"),
  },
  {
    workspace_member_id: 8,
    user_id: 5,
    workspace_id: 3,
    role: "MEMBER",
    joined_at: new Date("2024-11-01T10:00:00Z"),
  },
  {
    workspace_member_id: 9,
    user_id: 6,
    workspace_id: 3,
    role: "MEMBER",
    joined_at: new Date("2024-11-01T10:00:00Z"),
  },
];
